### ISSUE TITLE
About ProgramVQVAE

### ISSUE THREAD

**Issue by hmax233** [tiangeluo/ShapeCompiler#1]
Thanks for your great work!
I'm very interested in the  ''program <=> point cloud '' and seen the scripts of ''point cloud => program'',  but I can't find the encoder of ProgramVQVAE. Is there scripts about encoding program input?

**Comment by hmax233** [comment]
And another question: when I run generate_pgm_condpts.py. It results
` from core.nn import SharedMLP

ModuleNotFoundError: No module named 'core' `.
The scripts are not complete or I miss some information?

**Comment by tiangeluo** [comment]
Hi @hmax233 , thank you for your quick attempts. 

I've updated the codebase along with more detailed installation instructions. The current version is successfully testified on my end. Could you please take a re-try? Please feel free to let me know if anything errors.

**Comment by tiangeluo** [comment]
Currently, Program ⇒ Point Clouds is a deterministic process as described in the paper. We would first execute the program and obtain voxels, and then further extract point clouds thereon. 

I've incorporated Program ⇒ Point Clouds codes in the script of Point Clouds ⇒ Program.

Hope the above solves your issue.

**Comment by hmax233** [comment]
Thanks for your reply and work sincerely! I ran the code successfully and understand the program=>point cloud process.
